### ISSUE TITLE
Cannot interrupt after failed validation

### ISSUE THREAD

**Issue by j-ulrich** [lnquy065/inquirer-interrupted-prompt#2]
If there is a `validate` function specified on the prompt, it is not possible to interrupt the prompt anymore after the validation failed.

So consider this example:
```js
const answers = await inquirer.prompt([
		{
			message: `Please enter something:`,
			name: "requiredInput",
			type: "input",
			validate: (input) => {
				if (input) {
					return true;
				}
				return "This input is required. Please enter something.";
			},
		}
	]);
```

If the user presses return without entering something, they are back at the prompt but it is not possible to interrupt this prompt anymore because of the [`takeUntil(events.line)`](https://github.com/lnquy065/inquirer-interrupted-prompt/blob/a8914df1283027a17af5d48db46067898deb9e5a/index.js#L19).

I guess instead it would be better to unsubscribe when the `super.run()` promise is resolved or rejected. But I'm not sure.

**Comment by lnquy065** [comment]
Hi, thank for your clue, i will check it

**Comment by lnquy065** [comment]
According your clue, I fixed this issue, please update to new version
