### ISSUE TITLE
Please add a type definition file to the package

### ISSUE THREAD

**Issue by ajvincent** [lnquy065/inquirer-interrupted-prompt#4]
https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html

I had [TypeScript errors](https://blog.atomist.com/declaration-file-fix/) from this line:
`import inquirerFileTreeSelection from 'inquirer-file-tree-selection-prompt';`

I'm writing a pretty dirty hack to get around this:

```typescript
async function getModuleDefault<T>(importPath: string) : Promise<T>
{
  const module = await import(importPath) as { default: T };
  return module.default;
}

const InterruptedPrompt = await getModuleDefault<
  {
    fromAll(inquirer: unknown) : void;
    from(prompt: unknown) : inquirer.prompts.PromptConstructor;
  }
>
(
  "inquirer-interrupted-prompt"
);
```

**Comment by lnquy065** [comment]
thanks for your details, I'm planning for TS support

**Comment by lnquy065** [comment]
typescript has been supported from version 3 and above, sorry for the late 🥹
